version: "3"

services:
  linkedfactory-pod:
    container_name: linkedfactory-pod
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    environment:
      - enilink.loginrequired=false
    volumes:
      - ./pod-data/workspace:/linkedfactory-pod/workspace
      - ./pod-data/deploy:/linkedfactory-pod/deploy
    ports:
      - 8080:8080
