name: Build and deploy to Github packages

# Controls when the action will run.
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - snapshots
    # Sequence of patterns matched against refs/tags
    tags:
      - v*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: sonatype

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4.1.1

      # Sets up JDK
      - name: Set up JDK
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'temurin'
          java-version: '17'

      # Runs the Maven build
      - name: Build and deploy with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn deploy -B