name: Publish Docker image

# Controls when the action will run.
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - snapshots
    # Sequence of patterns matched against refs/tags
    tags:
      - v*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      # Sets up JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v3.4.0
        with:
          distribution: 'temurin'
          java-version: '11'

      # Runs the Maven build
      - name: Build server with Maven
        run: mvn package -Pserver
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: linkedfactory/linkedfactory-pod

      - name: Set version env variable
        run: echo "PROJECT_VERSION=$(< server/target/version.txt)" >> $GITHUB_ENV
      
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: linkedfactory/linkedfactory-pod:${{ env.PROJECT_VERSION }},linkedfactory/linkedfactory-pod:latest
          labels: ${{ steps.meta.outputs.labels }}
